### ISSUE TITLE
How i can join your Hado project server? 

### ISSUE THREAD

**Issue by elenakrittik** [TheMisterSenpai/Hado#1]
Hi, how i can join the projects server, its image was demonstrated at README.md file?
Привет, как я могу зайти на сервер проекта, его картинка была показана в файле README.md ?

Im writing this here because i didnt know how i can contact you anywhere else
Я пишу это здесь, потому что не знаю как еще связаться с вами где-нибудь еще

**Comment by TheMisterSenpai** [comment]
Вот ссылка на сервер поддержки: https://discord.gg/qAaw5kzzBn

**Comment by elenakrittik** [comment]
Благодарю!
